from pathlib import Path

def write_pyproject_toml(project_root: Path, pkgname: str) -> None:
    """
    Write a template pyproject.toml into the new package root.
    Ensures the generated package is pip-installable and PyPI-ready.
    """
    content = f"""\
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{pkgname}"
version = "0.1.0"
description = "A Python package scaffold generated by init_python_package"
authors = [{{ name = "Your Name" }}]
readme = "README.md"
requires-python = ">=3.9"
license = "Apache-2.0"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.optional-dependencies]
dev = ["pytest", "flake8"]

[project.scripts]
{pkgname}-cli = "{pkgname}.main:cli"

[tool.setuptools.packages.find]
include = ["{pkgname}"]
"""
    pyproject_path = project_root / "pyproject.toml"
    pyproject_path.write_text(content, encoding="utf-8")
    print(f"Created pyproject.toml at {pyproject_path}")